version: '3.4'
services:
  web_app:
    build:
      context: ./web_app
      dockerfile: DOCKERFILE
      target: sut
    ports:
      - 3000:3000
    environment:
      - POSTGRES_DB=app_test_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://user:password@postgres/app_test_db
  postgres:
    image: postgres:10.2
    environment:
      - POSTGRES_DB=app_test_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  sut:
    build:
      context: ./e2e
      dockerfile: DOCKERFILE
    ports:
      - 5000:5000
    environment:
      - POSTGRES_DB=app_test_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://user:password@postgres/app_test_db
      - APP_HOST=http://web_app:3000

