version: '3.4'
services:
  postgres:
    image: postgres:10.2
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  
