FROM node:9.6

WORKDIR /app

COPY ./.npmrc /app/
COPY ./.eslintrc /app/
COPY ./package.json /app/
RUN npm install --production

COPY ./lib /app/lib
COPY ./bin /app/bin

COPY ./migrations /app/migrations

CMD npm start

# Expose port
EXPOSE 3000